# Generated by Django 4.1.5 on 2023-01-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodo',
            name='order',
            field=models.IntegerField(verbose_name='相对顺序'),
        ),
    ]
