# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'RxSwiftStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RxSwiftStudy
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxTheme'
  pod 'RxGesture'
  pod 'ReactorKit'
  pod 'HandyJSON'
  pod 'SwiftyJSON'
  pod 'SwifterSwift'
  pod 'LookinServer', :configurations => ['Debug']

  target 'RxSwiftStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftStudyUITests' do
    # Pods for testing
  end

end
